### ISSUE TITLE
Pause and resume playing functionality

### ISSUE THREAD

**Issue by zork32** [meltaxa/jukebox-portal#2]
First of all, thank you for this cool project.
My Question:
I want to implement a pause and resume functionality. When removing the NFC tag it should pause the playback. When insert the same NFC tag again, the playback should continue at the same position. 
Is this easily possible with the used libraries?

**Comment by meltaxa** [comment]
Hi @zork32, it is indeed possible to do by watching for the tag "removed" status and calling the Spotify blueprint pause function. Pausing MP3 files will be challenging with the current procedures. Consideration to which tag is removed and only pausing the currently playing tag should be made. For example, if both Ironman and Emmet are on the pads with Ironman playing, only removing the Ironman tag should pause the track. Removing Emmet should do nothing.

**Comment by zork32** [comment]
Hi **@meltaxa**, thank you for your quick response.

"...Consideration to which tag is removed and only pausing the currently playing tag should be made. For example, if both Ironman and Emmet are on the pads with Ironman playing, only removing the Ironman tag should pause the track. Removing Emmet should do nothing."

Exactly! For me it would also be fine if this functionality would only work with one NFC tag on the pad.

My setup is currently: No plugged Monitor, autostart app over LXSession and use of mp3 only.

**Comment by meltaxa** [comment]
@zork32, I've added the pause and resume functionality to Spotify tracks and MP3 files. Test by checking out and pulling the code from the feature-music-pause-and-resume branch.

**Comment by meltaxa** [comment]
Made a few more enhancements, mostly with making the interactions more robust.

**Comment by meltaxa** [comment]
Also if in "MP3 only mode" (ie. no Spotify), you no longer need to visit the app web page after startup. The README quick install instructions has been updated to reflect this.

**Comment by meltaxa** [comment]
Merged to master.
