### ISSUE TITLE
System commands via NFC tags

### ISSUE THREAD

**Issue by zork32** [meltaxa/jukebox-portal#3]
Hi,
Is it possible to execute system commands via NFC tags? For example, an NFC tag for system shutdown or volume up / down?

**Comment by meltaxa** [comment]
Hi @zork32. Checkout branch offline-fix-and-command-feature for the feature. Example usage:

    043fd8daa74881:
        # Run a system command.
        name: Unix name
        command: uname -a

The command key can also be used in conjunction with the spotify or mp3 keys, as seen in the tags.yml-sample file.
