### ISSUE TITLE
function generates errors if no internet connection is available

### ISSUE THREAD

**Issue by zork32** [meltaxa/jukebox-portal#4]
[https://github.com/meltaxa/jukebox-portal/blob/d46530b47d33f7b45abd5690dda81008c6ac2b0e/app/__init__.py#L30](https://github.com/meltaxa/jukebox-portal/blob/d46530b47d33f7b45abd5690dda81008c6ac2b0e/app/__init__.py#L30)

'Check for updates' function generates errors if no internet connection is available.

**Comment by meltaxa** [comment]
Hi @zork32. Checkout branch offline-fix-and-command-feature for the fix.
